"""initial schema per spec section 6

Revision ID: 04fb52b0a190
Revises: 
Create Date: 2026-09-08 14:12:51.234166

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '04fb52b0a190'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('course_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('prerequisite_ids', sa.JSON(), nullable=False),
    sa.Column('resource_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_course_id'), ['course_id'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=6), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'method', 'path', 'key', name='ux_idempotency')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_student_id'), ['student_id'], unique=False)

    op.create_table('llm_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_student_id'), ['student_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('course_id', sa.String(length=40), nullable=False),
    sa.Column('primary_concept_id', sa.String(length=40), nullable=False),
    sa.Column('family_id', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('public_options', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('private_answer', sa.JSON(), nullable=False),
    sa.Column('private_hints', sa.JSON(), nullable=False),
    sa.Column('numeric_config', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_primary_concept_id'), ['primary_concept_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('daily_minutes BETWEEN 5 AND 120', name='ck_student_daily_minutes'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_token_hash'), ['token_hash'], unique=True)

    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('input_state_version', sa.Integer(), nullable=False),
    sa.Column('planner_source', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=True),
    sa.Column('fallback_reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_student_id'), ['student_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=40), nullable=False),
    sa.Column('target_concept_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_student_id'), ['student_id'], unique=False)

    op.create_table('mastery_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=40), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('formula_version', sa.String(length=10), nullable=False),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mastery_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mastery_snapshots_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mastery_snapshots_student_id'), ['student_id'], unique=False)

    op.create_table('mastery_states',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=40), nullable=False),
    sa.Column('estimate', sa.Float(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('evidence_strength', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recent_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('review_due_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'concept_id')
    )
    op.create_table('memory_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence_event_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_facts_student_id'), ['student_id'], unique=False)

    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_student_id'), ['student_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ordered_concept_ids', sa.JSON(), nullable=False),
    sa.Column('active_task_ids', sa.JSON(), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_student_id'), ['student_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_task_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_student_id'), ['student_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_student_id'), ['student_id'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('assessment_id', sa.String(length=36), nullable=True),
    sa.Column('question_id', sa.String(length=40), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('solution_seen', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(task_id IS NULL) <> (assessment_id IS NULL)', name='ck_exercise_single_owner'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_task_id'), ['task_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('hint_level_at_submission', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_student_id'), ['student_id'], unique=False)

    op.create_table('evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=40), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=60), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=60), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('score IN (0, 1)', name='ck_evidence_score'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidences_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ux_evidence_student_family_eligible', ['student_id', 'family_id'], unique=True, sqlite_where=sa.text('eligible = 1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.drop_index('ux_evidence_student_family_eligible', sqlite_where=sa.text('eligible = 1'))
        batch_op.drop_index(batch_op.f('ix_evidences_student_id'))
        batch_op.drop_index(batch_op.f('ix_evidences_concept_id'))
        batch_op.drop_index(batch_op.f('ix_evidences_attempt_id'))

    op.drop_table('evidences')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_exercise_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_task_id'))
        batch_op.drop_index(batch_op.f('ix_exercises_student_id'))
        batch_op.drop_index(batch_op.f('ix_exercises_assessment_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_student_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_goal_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_concept_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_student_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_goal_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_student_id'))
        batch_op.drop_index(batch_op.f('ix_plans_goal_id'))

    op.drop_table('plans')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_student_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_goal_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('memory_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_facts_student_id'))

    op.drop_table('memory_facts')
    op.drop_table('mastery_states')
    with op.batch_alter_table('mastery_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mastery_snapshots_student_id'))
        batch_op.drop_index(batch_op.f('ix_mastery_snapshots_concept_id'))

    op.drop_table('mastery_snapshots')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_student_id'))
        batch_op.drop_index(batch_op.f('ix_goals_course_id'))

    op.drop_table('goals')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_student_id'))
        batch_op.drop_index(batch_op.f('ix_events_session_id'))

    op.drop_table('events')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_student_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_session_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_token_hash'))

    op.drop_table('students')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_primary_concept_id'))
        batch_op.drop_index(batch_op.f('ix_questions_family_id'))
        batch_op.drop_index(batch_op.f('ix_questions_course_id'))

    op.drop_table('questions')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_student_id'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_student_id'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_course_id'))

    op.drop_table('concepts')
    # ### end Alembic commands ###
