"""plan node status snapshot

Revision ID: 510a806a5200
Revises: 04fb52b0a190
Create Date: 2026-09-08 16:20:56.139675

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '510a806a5200'
down_revision: Union[str, None] = '04fb52b0a190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_status_snapshot', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('node_status_snapshot')

    # ### end Alembic commands ###
